/* DiscordMod installer (Windows, Discord Stable).
 *
 * What it does:
 *   1. Finds the newest Discord Stable  app-<version>\resources  folder.
 *   2. Backs up the original  app.asar  ->  _app.asar  (once).
 *   3. Generates a thin shim (index.js + preload.js) that:
 *        - loads the ORIGINAL app from _app.asar untouched
 *        - patches BrowserWindow to chain-load our preload
 *        - injects our renderer bundle into the page's main world
 *   4. Packs the shim into a new app.asar.
 *
 * Re-run after every Discord update (updates create a fresh app-<version> folder).
 * Discord MUST be fully quit (including the tray icon) before running.
 */
const fs = require("fs");
const path = require("path");
const asar = require("@electron/asar");

const RENDERER_PATH = path.join(__dirname, "src", "renderer", "renderer.js");
const LOG_PATH = path.join(__dirname, "logs", "discord-console.log");

function fail(msg) {
  console.error("\n[install] ERROR: " + msg + "\n");
  process.exit(1);
}

function discordResources() {
  const base = path.join(process.env.LOCALAPPDATA || "", "Discord");
  if (!fs.existsSync(base)) fail("Discord Stable not found at " + base);

  const appDirs = fs
    .readdirSync(base)
    .filter((d) => d.startsWith("app-"))
    .map((d) => path.join(base, d))
    .filter((d) => fs.existsSync(path.join(d, "resources")))
    .sort();

  if (!appDirs.length) fail("no app-<version> folder with resources/ under " + base);
  const newest = appDirs[appDirs.length - 1];
  return path.join(newest, "resources");
}

function buildShim(tmpDir, origAsarPath, originalMain) {
  // Absolute paths baked in as JSON-safe string literals.
  const ORIG = JSON.stringify(path.join(origAsarPath, originalMain));
  const RENDERER = JSON.stringify(RENDERER_PATH);

  const LOG = JSON.stringify(LOG_PATH);

  const indexJs = `
// DiscordMod shim — generated by install.js. Loads original app + patches BrowserWindow.
const Module = require("module");
const path = require("path");
const fs = require("fs");

const PRELOAD = path.join(__dirname, "preload.js");
const LOG_PATH = ${LOG};
const RENDERER_PATH = ${RENDERER};

// Fresh log each launch so the reader always sees the current session.
try {
  fs.mkdirSync(path.dirname(LOG_PATH), { recursive: true });
  fs.writeFileSync(LOG_PATH, "=== DiscordMod session " + new Date().toISOString() + " ===\\n");
} catch (e) {}

// Hot-reload: watch the renderer's DIRECTORY (robust against editors that
// replace the file, which breaks a single-file fs.watch on Windows) and reload
// EVERY window on change. Reloading re-runs preload -> re-injects renderer.
// No process kill, so the session DB is never corrupted / no logout.
let _watchAttached = false;
function attachReloadWatch(electronModule) {
  if (_watchAttached) return;
  _watchAttached = true;
  const dir = path.dirname(RENDERER_PATH);
  const file = path.basename(RENDERER_PATH);
  try {
    let timer = null;
    fs.watch(dir, { persistent: false }, function (evt, name) {
      if (name && name !== file) return;
      clearTimeout(timer);
      timer = setTimeout(function () {
        try {
          logLine(1, "[DCMod] renderer.js changed -> re-injecting into all windows");
          const newCode = fs.readFileSync(RENDERER_PATH, "utf8");
          // Reset the guard then re-run the renderer in-place — no page reload needed.
          const reinjectCode = "window.__DCMOD_LOADED__ = false; " + newCode;
          const wins = electronModule.BrowserWindow.getAllWindows();
          for (const w of wins) {
            try {
              w.webContents.executeJavaScript(reinjectCode).catch(function (e) {
                logLine(3, "[DCMod] reinject failed: " + String(e));
              });
            } catch (e) {
              logLine(3, "[DCMod] reinject threw: " + String(e));
            }
          }
        } catch (e) {}
      }, 300);
    });
  } catch (e) {}
}

// Buffer log lines and flush asynchronously — sync appendFileSync per console
// line stalls the MAIN process (Discord is chatty). Batch + async = no UI jank.
let _logBuf = [];
let _logTimer = null;
function _flushLog() {
  _logTimer = null;
  if (!_logBuf.length) return;
  const chunk = _logBuf.join("");
  _logBuf = [];
  fs.appendFile(LOG_PATH, chunk, function () {});
}
function logLine(level, message) {
  try {
    const msg = String(message);
    // Keep the file small: only our lines + real errors.
    const isOurs = msg.indexOf("DCMod") !== -1;
    const isError = level === 3 || level === "error";
    // Drop Discord's chronic warning spam that floods the file.
    const isNoise =
      msg.indexOf("preloaded using link preload") !== -1 ||
      msg.indexOf("PostMessageTransport") !== -1 ||
      msg.indexOf("was preloaded using") !== -1;
    if (!isOurs && (!isError || isNoise)) return;
    _logBuf.push(new Date().toISOString() + " [" + level + "] " + msg + "\\n");
    if (!_logTimer) _logTimer = setTimeout(_flushLog, 250);
  } catch (e) {}
}

const origLoad = Module._load;
Module._load = function (request, parent, isMain) {
  const mod = origLoad.apply(this, arguments);
  if (request === "electron" && mod && mod.BrowserWindow && !mod.__dcmodPatched) {
    const RealBW = mod.BrowserWindow;
    class PatchedBrowserWindow extends RealBW {
      constructor(options) {
        try {
          if (options && options.webPreferences) {
            if (options.webPreferences.preload) {
              const _origPreload = options.webPreferences.preload;
              // Pass the original preload path PER-WINDOW via additionalArguments (arrives in
              // that preload process's process.argv). A single process.env slot is a race: a
              // second window created before the first's preload runs would clobber it. env is
              // kept only as a fallback for the (normal) single-window case.
              options.webPreferences.additionalArguments = (options.webPreferences.additionalArguments || []).concat(
                "--dcmod-original-preload=" + _origPreload
              );
              process.env.DCMOD_ORIGINAL_PRELOAD = _origPreload;
              options.webPreferences.preload = PRELOAD;
            }
            // Re-enable DevTools (Discord Stable forces this off).
            options.webPreferences.devTools = true;
          }
        } catch (e) {}
        super(options);
        try {
          // Bind Ctrl+Shift+I ourselves so it works regardless of Discord's menu.
          // Open DevTools DETACHED — docked DevTools share the BrowserWindow and
          // Chromium enforces a combined minimum width, so Discord can't shrink
          // horizontally as far as expected while the console is open.
          this.webContents.on("before-input-event", (event, input) => {
            if (input.control && input.shift && (input.key === "I" || input.key === "i")) {
              if (this.webContents.isDevToolsOpened()) {
                this.webContents.closeDevTools();
              } else {
                this.webContents.openDevTools({ mode: "detach" });
              }
            }
          });
          // Mirror renderer console -> log file (handles old + new Electron signatures).
          this.webContents.on("console-message", function () {
            const a = arguments;
            if (a.length && typeof a[0] === "object" && a[0] && "message" in a[0]) {
              logLine(a[0].level, a[0].message);
            } else {
              logLine(a[0], a[1]);
            }
          });
          // Only the main app window gets our preload swapped in -> watch it for hot-reload.
          if (options && options.webPreferences && options.webPreferences.preload === PRELOAD) {
            attachReloadWatch(mod);
          }
        } catch (e) {}
      }
    }
    // Preserve statics (fromId, getAllWindows, etc.)
    Object.setPrototypeOf(PatchedBrowserWindow, RealBW);
    const proxy = new Proxy(mod, {
      get(t, p) {
        if (p === "BrowserWindow") return PatchedBrowserWindow;
        if (p === "__dcmodPatched") return true;
        return t[p];
      },
    });
    return proxy;
  }
  return mod;
};

// Window-control bridge (main side). This frozen Discord build's own renderer→main
// window-control IPC is dead (DiscordNative.window.minimize/maximize no-op), so the
// titlebar min/maximize buttons do nothing. The Electron window is fully capable, so
// we perform the action directly on the sender's window. Renderer triggers via the
// DCModNative bridge exposed in preload.js.
try {
  const electron = require("electron");
  electron.ipcMain.on("DCMOD_WINCTL", function (event, action) {
    try {
      const win = electron.BrowserWindow.fromWebContents(event.sender);
      if (!win) return;
      if (action === "minimize") win.minimize();
      else if (action === "toggleMaximize") win.isMaximized() ? win.unmaximize() : win.maximize();
      else if (action === "close") win.close();
    } catch (e) {}
  });
} catch (e) {}

// Hand control to the original, untouched Discord app.
require(${ORIG});
`.trimStart();

  const preloadJs = `
// DiscordMod preload — chains Discord's original preload, then injects renderer into main world.
const fs = require("fs");
const { webFrame, contextBridge, ipcRenderer } = require("electron");
const RENDERER_PATH = ${RENDERER};

// Expose a working window-control bridge to the page's main world. The renderer
// calls these because this build's DiscordNative.window.minimize/maximize are dead.
try {
  const winApi = {
    minimize: function () { ipcRenderer.send("DCMOD_WINCTL", "minimize"); },
    toggleMaximize: function () { ipcRenderer.send("DCMOD_WINCTL", "toggleMaximize"); },
    close: function () { ipcRenderer.send("DCMOD_WINCTL", "close"); },
  };
  try {
    contextBridge.exposeInMainWorld("DCModNative", winApi); // contextIsolation ON (Discord default)
  } catch (e) {
    window.DCModNative = winApi; // fallback if isolation is off
  }
} catch (e) {
  console.error("[DCMod] window-control bridge failed:", e);
}

// 1) Run Discord's real preload so DiscordNative / window APIs exist.
//    Prefer the per-window arg (race-free); fall back to the env var.
try {
  let origPreload = process.env.DCMOD_ORIGINAL_PRELOAD;
  try {
    const arg = (process.argv || []).find(function (a) { return a.indexOf("--dcmod-original-preload=") === 0; });
    if (arg) origPreload = arg.slice("--dcmod-original-preload=".length);
  } catch (e) {}
  if (origPreload) {
    require(origPreload);
  }
} catch (e) {
  console.error("[DCMod] failed to chain original preload:", e);
}

// 2) Inject our renderer into the page's MAIN WORLD via executeJavaScript.
//    This bypasses the page CSP that blocks inline <script> elements.
try {
  const code = fs.readFileSync(RENDERER_PATH, "utf8");
  webFrame.executeJavaScript(code).catch((e) => console.error("[DCMod] inject failed:", e));
} catch (e) {
  console.error("[DCMod] failed to read renderer:", e);
}
`.trimStart();

  const pkg = { name: "discord", main: "index.js" };

  fs.mkdirSync(tmpDir, { recursive: true });
  fs.writeFileSync(path.join(tmpDir, "index.js"), indexJs);
  fs.writeFileSync(path.join(tmpDir, "preload.js"), preloadJs);
  fs.writeFileSync(path.join(tmpDir, "package.json"), JSON.stringify(pkg, null, 2));
}

async function main() {
  if (!fs.existsSync(RENDERER_PATH)) fail("renderer not found at " + RENDERER_PATH);

  const resources = discordResources();
  const appAsar = path.join(resources, "app.asar");
  const backup = path.join(resources, "_app.asar");

  console.log("[install] resources:", resources);

  // Back up the original once. If _app.asar already exists we're re-injecting.
  if (!fs.existsSync(backup)) {
    if (!fs.existsSync(appAsar)) fail("app.asar not found — unexpected Discord layout");
    fs.renameSync(appAsar, backup);
    console.log("[install] backed up original -> _app.asar");
  } else {
    console.log("[install] _app.asar backup already present (re-injecting)");
    if (fs.existsSync(appAsar)) fs.rmSync(appAsar, { force: true });
  }

  // Read original entry point from the backed-up asar.
  let originalMain = "index.js";
  try {
    const pkgRaw = asar.extractFile(backup, "package.json");
    originalMain = JSON.parse(pkgRaw.toString("utf8")).main || "index.js";
  } catch (e) {
    fail("could not read original package.json from _app.asar: " + e.message);
  }
  console.log("[install] original entry:", originalMain);

  // Build shim and pack into new app.asar.
  const tmpDir = path.join(__dirname, ".shim-build");
  fs.rmSync(tmpDir, { recursive: true, force: true });
  buildShim(tmpDir, backup, originalMain);

  await asar.createPackage(tmpDir, appAsar);
  fs.rmSync(tmpDir, { recursive: true, force: true });

  console.log("\n[install] DONE ✓");
  console.log("  -> Fully quit Discord (right-click tray icon > Quit), then relaunch.");
  console.log("  -> Open DevTools (Ctrl+Shift+I) console; you should see '[DCMod] ready'.");
  console.log("  -> Edit src/renderer/renderer.js + restart Discord to iterate (no re-install).");
  console.log("  -> After a Discord update, re-run:  node install.js\n");
}

if (require.main === module) {
  main().catch((e) => fail(e.stack || String(e)));
}

module.exports = { buildShim };
